# Retail Store Sales Data Cleaning and Preprocessing

## Project Overview

This project focuses on cleaning and preprocessing a real-world retail store sales dataset using Python and Pandas.

The dataset contains transaction details such as customer information, product categories, prices, quantities, payment methods, locations, transaction dates, and discount information.

The main objective is to identify and handle missing values, check duplicate records, correct data types, detect potential outliers, perform feature engineering, and export a clean dataset for further analysis.

## Project Objective

The objective of this project is to prepare a messy retail dataset for further analysis by:

- Loading the raw dataset using Pandas
- Identifying missing values and handling them appropriately
- Checking and removing duplicate records
- Correcting incorrect data types
- Detecting potential outliers
- Creating useful features from transaction dates
- Calculating revenue from price and quantity
- Exporting the final cleaned dataset as `clean_dataset.csv`

## Dataset Information

The dataset used in this project is a retail store sales dataset containing more than 10,000 transaction records.

### Dataset Details

- **Number of rows:** 12,575
- **Number of columns:** 11
- **Data type:** Retail transaction data
- **Source file:** `retail_store_sales.xlsx.csv`

### Main Information Available

The dataset contains:
- Transaction ID
- Customer ID
- Product Category
- Item
- Price Per Unit
- Quantity
- Total Spent
- Payment Method
- Location
- Transaction Date
- Discount Applied

In [41]:
import pandas as pd

In [42]:
import os
print(os.getcwd())

c:\Users\Barath\OneDrive\Desktop\Retail_Data_Cleaning

In [43]:
import os

print(os.listdir())

['clean_dataset.csv', 'retail_data_cleaning.ipynb', 'retail_store_sales.xlsx.csv']

In [44]:
df = pd.read_csv("retail_store_sales.xlsx.csv")

In [45]:
print(df.shape)

(12575, 11)

In [46]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [47]:
print(df.columns)

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='str')

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

In [49]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.dtypes

Transaction ID          str
Customer ID             str
Category                str
Item                    str
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Discount Applied     object
dtype: object

In [52]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [53]:
Q1 = df["Total Spent"].quantile(0.25)
Q3 = df["Total Spent"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Q1: 51.0
Q3: 192.0
IQR: 141.0
Lower Limit: -160.5
Upper Limit: 403.5

In [54]:
outliers = df[df["Total Spent"] > upper_limit]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 60

In [55]:
outliers[["Transaction ID", "Price Per Unit", "Quantity", "Total Spent"]]

      Transaction ID  Price Per Unit  Quantity  Total Spent
27       TXN_1599706            41.0      10.0        410.0
133      TXN_2953434            41.0      10.0        410.0
339      TXN_4374445            41.0      10.0        410.0
869      TXN_1814138            41.0      10.0        410.0
1060     TXN_3710081            41.0      10.0        410.0
1088     TXN_1273334            41.0      10.0        410.0
1468     TXN_1938135            41.0      10.0        410.0
1505     TXN_8520397            41.0      10.0        410.0
1568     TXN_8048041            41.0      10.0        410.0
1950     TXN_1860120            41.0      10.0        410.0
1983     TXN_6924479            41.0      10.0        410.0
2153     TXN_5338814             NaN      10.0        410.0
2180     TXN_1172555            41.0      10.0        410.0
2182     TXN_4047143            41.0      10.0        410.0
2540     TXN_2208547            41.0      10.0        410.0
2658     TXN_1227978            41.0      10.0        410.0
3036     TXN_2624160            41.0      10.0        410.0
3094     TXN_7177583            41.0      10.0        410.0
3778     TXN_7898457            41.0      10.0        410.0
4526     TXN_3142066            41.0      10.0        410.0
4780     TXN_3465682            41.0      10.0        410.0
5364     TXN_8384530            41.0      10.0        410.0
5745     TXN_3855536             NaN      10.0        410.0
5756     TXN_4286472            41.0      10.0        410.0
5819     TXN_4456347            41.0      10.0        410.0
5969     TXN_2058333            41.0      10.0        410.0
6174     TXN_4428473            41.0      10.0        410.0
6374     TXN_6219786            41.0      10.0        410.0
6611     TXN_7056530            41.0      10.0        410.0
6785     TXN_6513125            41.0      10.0        410.0
7272     TXN_4858882            41.0      10.0        410.0
7372     TXN_8830035            41.0      10.0        410.0
7520     TXN_9553259            41.0      10.0        410.0
7716     TXN_9628331            41.0      10.0        410.0
7769     TXN_8688342            41.0      10.0        410.0
8076     TXN_3858239            41.0      10.0        410.0
8508     TXN_4771109             NaN      10.0        410.0
8596     TXN_2288041             NaN      10.0        410.0
8611     TXN_3342443            41.0      10.0        410.0
8845     TXN_4208189            41.0      10.0        410.0
8852     TXN_9745509            41.0      10.0        410.0
9214     TXN_2971834            41.0      10.0        410.0
9378     TXN_8837607            41.0      10.0        410.0
9620     TXN_2386101            41.0      10.0        410.0
9760     TXN_7254589            41.0      10.0        410.0
9884     TXN_8716794            41.0      10.0        410.0
9963     TXN_6651911            41.0      10.0        410.0
10103    TXN_1654267            41.0      10.0        410.0
10884    TXN_5286547            41.0      10.0        410.0
11093    TXN_5710989            41.0      10.0        410.0
11608    TXN_7169895            41.0      10.0        410.0
11610    TXN_6812555            41.0      10.0        410.0
11662    TXN_5870737            41.0      10.0        410.0
11670    TXN_9777368            41.0      10.0        410.0
12176    TXN_5150834            41.0      10.0        410.0
12189    TXN_9791556            41.0      10.0        410.0
12192    TXN_1657130            41.0      10.0        410.0
12209    TXN_1113295            41.0      10.0        410.0
12542    TXN_7484072            41.0      10.0        410.0
12557    TXN_7239201            41.0      10.0        410.0

In [56]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [57]:
df["Item"] = df["Item"].fillna(df["Item"].mode()[0])

In [58]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df["Price Per Unit"].median()
)

In [59]:
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

In [60]:
df["Total Spent"] = df["Total Spent"].fillna(
    df["Price Per Unit"] * df["Quantity"]
)

In [61]:
df["Discount Applied"] = df["Discount Applied"].fillna(False)

In [62]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [63]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [64]:
print(df["Transaction Date"].dtype)

datetime64[us]

In [65]:
print("Invalid dates:", df["Transaction Date"].isnull().sum())

Invalid dates: 0

In [66]:
df["Year"] = df["Transaction Date"].dt.year

In [67]:
df["Month"] = df["Transaction Date"].dt.month

In [68]:
df["Month Name"] = df["Transaction Date"].dt.month_name()

In [69]:
df["Revenue"] = df["Price Per Unit"] * df["Quantity"]

In [70]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Year,Month,Month Name,Revenue
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,2024,4,April,185.0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,2023,7,July,261.0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,2022,10,October,43.0
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,False,2022,5,May,247.5
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,2022,10,October,87.5

In [71]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [72]:
df.dtypes

Transaction ID                 str
Customer ID                    str
Category                       str
Item                           str
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Discount Applied            object
Year                         int32
Month                        int32
Month Name                     str
Revenue                    float64
dtype: object

In [73]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
Year                0
Month               0
Month Name          0
Revenue             0
dtype: int64

In [74]:
print("Final dataset shape:", df.shape)

Final dataset shape: (12575, 15)

In [75]:
df.describe()

,Price Per Unit,Quantity,Total Spent,Transaction Date,Year,Month,Revenue
count,12575.000000,12575.000000,12575.000000,12575,12575.000000,12575.000000,12575.000000
mean,23.348191,5.558648,130.208111,2023-07-12 20:23:41.105367,2023.042386,6.366441,130.114950
min,5.000000,1.000000,5.000000,2022-01-01 00:00:00,2022.000000,1.000000,5.000000
25%,14.000000,3.000000,52.000000,2022-09-30 00:00:00,2022.000000,3.000000,55.000000
50%,23.000000,6.000000,110.000000,2023-07-13 00:00:00,2023.000000,6.000000,111.000000
75%,32.000000,8.000000,192.000000,2024-04-24 00:00:00,2024.000000,9.000000,192.000000
max,41.000000,10.000000,410.000000,2025-01-18 00:00:00,2025.000000,12.000000,410.000000
std,10.480413,2.790160,93.580667,NaN,0.855581,3.503156,92.327187

In [76]:
df.head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Year,Month,Month Name,Revenue
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,2024,4,April,185.0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,2023,7,July,261.0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,2022,10,October,43.0
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,False,2022,5,May,247.5
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,2022,10,October,87.5
5,TXN_7482416,CUST_09,Patisserie,Item_2_BEV,23.0,10.0,200.0,Credit Card,Online,2023-11-30,False,2023,11,November,230.0
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True,2023,6,June,40.0
7,TXN_1372952,CUST_21,Furniture,Item_2_BEV,33.5,6.0,201.0,Digital Wallet,In-store,2024-04-02,True,2024,4,April,201.0
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False,2023,4,April,27.5
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False,2024,3,March,109.5

In [77]:
df.to_csv("clean_dataset.csv", index=False)

print("Clean dataset exported successfully!")

Clean dataset exported successfully!